### ISSUE TITLE
Using freki on host connected to network through Proxy Server.

### ISSUE THREAD

**Issue by kalyan-kumar** [kung-foo/freki#5]
My system connects to the internet via a HTTP proxy. I saw the documentation specified freki usage while on a TCP proxy (which I assume must be SOCKS proxy), when I tried working with similar rules for HTTP proxy, I couldn't get freki working. Am I doing anything wrong, or is this support to be added to freki yet?

**Comment by kung-foo** [comment]
Hi @kalyan-kumar, that's not really how freki works. When you have a rule like this:

```yaml
  - match: tcp dst port 555
    type: proxy
    target: tcp://portquiz.net:666
```
That means that any incoming connection on TCP port 555 will be accepted, and then proxied to portquiz.net:666.

This is not the same thing as a HTTP proxy. Rather it is really just shuffling bytes between two TCP connections.
